VERSION = 1.0.0.0
VERSION_STR=1.0
QMAKE_TARGET_COMPANY="Neusoft Corporation"
QMAKE_TARGET_COPYRIGHT="Neusoft Corporation (DaLian) Co. Ltd."
QMAKE_TARGET_PRODUCT="LVGL-EJanus2.0"
QMAKE_TARGET_DESCRIPTION="LVGL-EJanus2.0"
RC_LANG = 0x0004
RC_ICONS = $$PWD/version.ico
DEFINES+=APP_VERSION_STR=\\\"$$VERSION_STR\\\"
